name: Upbond DID
on:
  push:
    branches: [master]

env:
  PRIVATEKEY: 40b0c9441457ad318cf9a3ccdd8fd7ea71c38d0fcb8fe798fde618422e31c8c9
  API: EP56D8EPKQTQP8ZUQGI7ZJSCR5ND83UHZG

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: hardhat compile
        run: yarn compile

      - name: hardhat test with GAS REPORT
        run: yarn test:gas
